### PR TITLE
Remove mention of url-arbiter

### PR DESCRIPTION
**Pull request by steventux**
Url arbiter has been removed from publishing API, update provider state
titles accordingly.

### CODE REVIEW

**Comment by alext** [comment]
I wonder whether we should reconsider the wording of these states so as to avoid having to make similar changes to them in the future.

Ideally we would phrase these in a way that doesn't mention any implementation details at all - ie it would be good if they didn't reference the content-store at all.

**Comment by steventux** [comment]
@alext I agree, I think @tuzz also made this point that we should remove mention of downstream applications. I'll add this to the PR.

**Comment by steventux** [comment]
@alext see https://github.com/alphagov/gds-api-adapters/commit/8aae1580a877fe21664fdba9e533e189edae4750 for rephrased descriptions

**Comment by alext** [comment]
https://github.com/alphagov/publishing-api/pull/118 will fix the tests on this end without breaking the tests in publishing-api.

**Pull request merged**
