### PR TITLE
Release 32.0.0

### PR DESCRIPTION
**Pull request by elliotcm**
Releases https://github.com/alphagov/gds-api-adapters/pull/538

### CODE REVIEW

**Comment by boffbowsh** [comment]
Why not 32.0.0?

**Comment by elliotcm** [comment]
While probably the right thing to do it felt weird releasing someone else's breaking change as though it was part of my work, even though that's effectively what I'm doing anyway.

**Comment by elliotcm** [comment]
@boffbowsh your opine?

**Comment by 36degrees** [comment]
Either way, might be worth having something documenting how releases work for this repo as I wasn't sure if a) I should create a release for my previous changes myself and b) how I'd even begin to do that.

**Comment by elliotcm** [comment]
@36degrees Releasing gem versions is detailed here: https://github.com/alphagov/styleguides/blob/master/rubygems.md

Though it isn't particularly clear about when how etc.  There's nothing special about this gem vs our others so perhaps we should beef up that documentation, unless someone knows of other docs somewhere else (I couldn't find anything in the opsmanual).

**Comment by 36degrees** [comment]
It'd be good to get this release out soon as we have some downstream stuff waiting on the changes that I made (which I now know I should have just released myself – live and learn 😄)

FWIW, I'd expect the next release to be 32.0.0.

**Comment by boffbowsh** [comment]
Yeah I'd expect 32.0.0, else I'd wonder where that release went.

**Comment by elliotcm** [comment]
Done.

**Comment by 36degrees** [comment]
LGTM 👍

**Comment by elliotcm** [comment]
@36degrees hit that butan

**Pull request merged**
