### PR TITLE
Bump gem version 30.0.1

### PR DESCRIPTION
**Pull request by christophwong**

### CODE REVIEW

**Comment by christophwong** [comment]
merged with @dougdroper

**Comment by tijmenb** [comment]
We really shouldn't merge our own PRs, slippery slope etc. Also the tests seem to be failing, is that related?

**Comment by christophwong** [comment]
@tijmenb I showed the PR to @dougdroper and it looked ok.
Sorry about the test, when we merged it, it was definitely green, but it might be because of this morning's Github's server issue that the webhook were showing wrong info. I will revert it and redo this.

**Comment by christophwong** [comment]
Oh actually the failing test seems to be a problem on jenkins and not this commit. As a rerun has fixed it.

**Comment by tijmenb** [comment]
:+1: great

**Pull request merged**
