### PR TITLE
Add test helper for get_linked_items

### PR DESCRIPTION
**Pull request by carvil**
This commit adds a test helper for `get_linked_items` and the corresponding test.

### CODE REVIEW

**Comment by Davidslv** [comment]
Ah! You were quicker than me to add it 👍 
LGTM

**Comment by Davidslv** [comment]
Can you add that change to the [CHANGELOG.md](https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md) please?

**Comment by carvil** [comment]
@Davidslv I will add this to the CHANGELOG on the next PR to bump the version of the gem if that's ok.

**Comment by Davidslv** [comment]
ok

**Pull request merged**
