### PR TITLE
Add `PublishingApiV2#get_content_items`

### PR DESCRIPTION
**Pull request by tijmenb**
This method is used to interact with the `/v2/content` endpoint on publishing-api.

Endpoint PR: alphagov/publishing-api#126

### CODE REVIEW

**Comment by benlovell** [comment]
Looks like the latest version of `tins` removed support for rubies less than 2. :cry:

**Comment by tijmenb** [comment]
@benlovell yes :( https://github.com/alphagov/gds-api-adapters/pull/387

**Comment by tijmenb** [comment]
The pact tests are failing here because the endpoint used here hasn't been implemented yet. Once https://github.com/alphagov/publishing-api/pull/126 has been merged it will be green.

**Pull request merged**
